### ISSUE TITLE
关于HASAC算法的Actor网络loss代码

### ISSUE THREAD

**Issue by liuda1064838990** [PKU-MARL/HARL#16]
请问HASAC算法的Actor网络loss设计中，关于Advantage的计算在哪里呢？我在off_policy_ha_runner看到的Actor的loss好像是等于-Q（s,a）+entropy项呢，感到有些迷惑和不解，如果您能够回复，万分感谢~

**Comment by guazimao** [comment]
Hello liuda1064838990. When HASAC learns the policies, there's no need to calculate the advantage. Each agent's policy $\pi^{i_m}$, in each state, should aim to maximize the soft Q function plus the expected future entropy. In other words, it should maximize $\underset{a^{i_m} \sim \pi^{i_m}}{\mathbb{E}}[Q^{i_{1:m}}(s, a^{1:m-1},a^{i_m})-log\pi^{i_m}]$. You can refer to section 4.2.2 of our [MEHARL](https://arxiv.org/abs/2306.10715) paper and the single-agent [SAC](https://arxiv.org/abs/1801.01290) paper for more details.
