### ISSUE TITLE
Tuned configs for Light Aircraft Game 

### ISSUE THREAD

**Issue by prinshul** [PKU-MARL/HARL#21]
Hi

Can you please share the tuned configs for Light Aircraft Game env for following algorithms:
Mappo
Maddpg
Hatpro
Happo
Haa2c

Thanks.

**Comment by Ivan-Zhong** [comment]
Sorry, we did not run those experiments.

**Comment by oldroad9** [comment]
Can you please share the tuned configs for Smac env for Mappo? 
I'd appreciate it if you could

**Comment by Ivan-Zhong** [comment]
Those configs are available in their [official repo](https://github.com/marlbenchmark/on-policy).
