### ISSUE TITLE
Question about env observability

### ISSUE THREAD

**Issue by prinshul** [PKU-MARL/HARL#22]
Hi,

Are all environments implemented with global observability?

Thanks.

**Comment by Ivan-Zhong** [comment]
No, some of them are not, for example MPE, SMAC, SMACv2, Bi-DexHands.

**Comment by prinshul** [comment]
Mujoco and LAG?

**Comment by Ivan-Zhong** [comment]
They are globally observable.

**Comment by prinshul** [comment]
Thanks.
Any pointers as to how to make them partially observable?

**Comment by guazimao** [comment]
Hi. You can refer to the original MAMujoco [repo](https://github.com/schroederdewitt/multiagent_mujoco) to make it partially observable. As for LAG, currently, it cannot be made partially observable.

**Comment by prinshul** [comment]
Thanks.
