### ISSUE TITLE
Question about N-step TD trick in on policy

### ISSUE THREAD

**Issue by Yuxin916** [PKU-MARL/HARL#25]
Hi! Sorry for bothering I need your help again. 

I noticed that there is no TD(n) trick in your on-policy runner. But i find it in off-policy algos instead. May i know why is that happen? Does it mean MAPPO can not do TD(n) or it is just engineerng work that can be done by future development :) 

Thank you

**Comment by Ivan-Zhong** [comment]
Hello. We implement GAE for on-policy algorithms and TD(n) for off-policy algorithms, which are commonly adopted practices. I think GAE embodies the notion of TD(n).

**Comment by Yuxin916** [comment]
Oh i see. Thank you for your explanation!
