### ISSUE TITLE
Request for Fine-Tuned YAML File for HASAC Algorithm

### ISSUE THREAD

**Issue by WentseChen** [PKU-MARL/HARL#28]
Hi team,

I appreciate the outstanding work you've done. I am currently working on HASAC implementation and require the fine-tuned YAML file. Could you please release the necessary YAML file, or provide information on the expected timeline for its release?

**Comment by guazimao** [comment]
Hi. You can refer to the Appendix H of [MEHARL](https://arxiv.org/abs/2306.10715) paper first. We have provided detailed hyperparameters for HASAC there.

**Comment by WentseChen** [comment]
Hi team, 

Could you please provide or let me know if you are planning to release the fine-tuned config of HASAC on the SMACv2 benchmark?
