### ISSUE TITLE
Have QMIX implement code ?

### ISSUE THREAD

**Issue by RayKr** [PKU-MARL/HARL#3]
![image](https://github.com/PKU-MARL/HARL/assets/10293675/dfcd7e7d-561f-42a0-91b4-e38f7aacedad)
There is a QMIX result in the experiment, but I can't find the QMIX code in this repository. Is there a QMIX implementation code available? Thanks. :)

**Comment by Ivan-Zhong** [comment]
Hello,

We did not implement QMIX in this repository. As clarified in our [paper](https://arxiv.org/abs/2304.09870), in SMAC and GRF we use the [implementation of QMIX](https://github.com/marlbenchmark/off-policy) by [Yu et al.](https://arxiv.org/abs/2103.01955), and in SMACv2 we use the [implementation of QMIX](https://github.com/benellis3/pymarl2) by [Ellis et al.](https://arxiv.org/abs/2212.07489).

**Comment by RayKr** [comment]
Sorry about another question, by reading the code, according to my understanding, hd3qn means dueling double deep q network, which is actually the Q-learning family method, it is known that Q-learning only has critic, but I found that the code also uses actor and critic, both are using the DuelingQNet model, I don't know if I understand it correctly, please ask why this design? Sincerly :)

**Comment by RayKr** [comment]
Thanks for your response. 👍 :)
