### ISSUE TITLE
The issue with runing off policy algorithm

### ISSUE THREAD

**Issue by xiaoliu-syd** [PKU-MARL/HARL#30]
The simulation with customized environment can not be run with off policy algorithm. It always stuck with warmup stage. While for the on policy algorithm, it is fine.

**Comment by xiaoliu-syd** [comment]
The off policy require a long time for the warmup step. I am wondering if this this step is necessary since my env is not that complex to go through such long time warmup.&nbsp; Besides that, after the warmup step, the reward is wired and it&nbsp; converged at the initial stage of training.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PKU-MARL/HARL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月23日(星期二) 晚上8:31
***@***.***&gt;;
抄送:&nbsp;"xiao ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PKU-MARL/HARL] The issue with runing off policy algorithm (Issue #30)





 
Hi. Could you provide more detailed information like error messages?

**Comment by guazimao** [comment]
Sorry for the late reply. In the warmup step, only random action sampling takes place. It is not necessary and can be skipped if it takes too long. Unfortunately, without detailed information about your customized environment, we cannot explain why the reward is weird.
