### ISSUE TITLE
 MAPPO continuous action space, act layer rescale 

### ISSUE THREAD

**Issue by Yuxin916** [PKU-MARL/HARL#31]
Hi! Thank you for your work! 

I have question about the act layer of MAPPO algo. the last action layer for continous case (Diaggussian - FixNorm distribution) output don't have any activation layer like tanh and upper and lower bond for according to environment action space for rescaling, it just directly output the value for all action dim. I am curious that may cause some value out of bond. 

I noticed you actually did this in off policy algos such as MADDPG. (deterministic_policy.py and plain_mlp.py)May i know why it is not in MAPPO?

**Comment by Ivan-Zhong** [comment]
Hello, thank you for your question. The implementations follow common practices, where PPO does not impose a final rescaling and DDPG rescales the output. I acknowledge that this may cause the PPO-based algorithms' outputs to exceed the action limits, but from experiments, it seems this does not lead to poor performance.
