### ISSUE TITLE
Config files for HASAC with Mujoco and spread

### ISSUE THREAD

**Issue by prinshul** [PKU-MARL/HARL#32]
Hi,

I referred to the paper for hyperparameters of HASAC with many-agent_swimmer_10x2. The plot is below:
![Screenshot 2024-02-15 at 11 42 53 AM](https://github.com/PKU-MARL/HARL/assets/13760669/b814f659-8906-462c-ab81-5d47ace65e6a)
Eval average episode len: 1000
Can you please share the config files for at least all Mujoco and both discrete and continuous simple spread environments for HASAC?

Thank you.

**Comment by guazimao** [comment]
Hi. We've updated all config files of HASAC on MAMuJoCo and MPE.
