### ISSUE TITLE
Issues About MultiDiscrete Action Space In Multi-Agent Environment Development

### ISSUE THREAD

**Issue by captain12321** [PKU-MARL/HARL#35]
First of all, thanks for sharing the source code to us so that we can benefit from your works.
Currently, I encounterd a problem when I wanted to develop a customized environment using the interface you have provided.
In my experiment, I want agents to output MultiDiscrete action like:

` self.action_space = Tuple([MultiDiscrete([5]+[20] * 10) for _ in range(self.R_UAVs)])`

that is, each agent output a eleven dimentional array. The first element of this array takes value from `0-5` while the other `10` elements behind take value from `0-19`.There is an expamle provided using `self.action_spaces.sample()`:

`Action Space Example: (array([ 2, 17,  1, 18, 10,  5, 12,  6,  3, 13, 11], dtype=int64), array([ 3, 17,  7,  7, 16,  1, 14, 15,  5,  5,  6], dtype=int64))`

The observation space of my experiment are as follow:

`self.share_observation_space = [Box(0.0, self.boundary*2, ((self.Tol_UAVs*2)*self.R_UAVs,),dtype=np.float64) for _ in range(self.R_UAVs)]`
`self.observation_space = [Box(0.0, self.boundary*2, (self.Tol_UAVs*2,),dtype=np.float64) for _ in range(self.R_UAVs)] `

But when I run the `HASAC` code, there is an error reported like this:

`Traceback (most recent call last):`
 ` File "train.py", line 98, in <module>`
   ` main()`
  `File "train.py", line 93, in main`
    `runner.run()`
 ` File "e:\harl\harl\harl\runners\off_policy_base_runner.py", line 283, in run`
    `self.train()`
  `File "e:\harl\harl\harl\runners\off_policy_ha_runner.py", line 162, in train`
    `actions[agent_id], _ = self.actor[`
  `File "e:\harl\harl\harl\algorithms\actors\hasac.py", line 67, in get_actions_with_logprobs`
    `logits = self.actor.get_logits(obs, available_actions)`
 ` File "e:\harl\harl\harl\models\policy_models\stochastic_mlp_policy.py", line 78, in get_logits`
    `return self.act.get_logits(actor_features, available_actions)`
 ` File "e:\harl\harl\harl\models\base\act.py", line 98, in get_logits`
    `action_distribution = action_out(x, available_actions)`
  `File "D:\miniconda\envs\harl\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl`
    `return forward_call(*input, **kwargs)`
  `File "e:\harl\harl\harl\models\base\distributions.py", line 55, in forward`
     `return FixedCategorical(logits=x)`
  `File "D:\miniconda\envs\harl\lib\site-packages\torch\distributions\categorical.py", line 64, in __init__`
    `super(Categorical, self).__init__(batch_shape, validate_args=validate_args)`
  `File "D:\miniconda\envs\harl\lib\site-packages\torch\distributions\distribution.py", line 53, in __init__`
    `raise ValueError("The parameter {} has invalid values".format(param))`
`ValueError: The parameter logits has invalid values`

It seems there's a problem when the algorithm outputs the possibility of the actions, But I don't know why.
I wonder if i should set `available_actions`,since I set it as `None` currently.
I am not sure what's wrong with it :( . Hope for your reply.

**Comment by guazimao** [comment]
Hi. According to the information you provided, the action space of your environment is of type gym.spaces.Tuple. I regret that our algorithms currently do not support Tuple action space. They only support box, discrete, and multidiscrete.

**Comment by captain12321** [comment]
Thanks，but it still can't work after i modified it to:
`self.action_space =[MultiDiscrete([5]+[20]*10) for _ in range(self.R_UAVs)]`
The error this time is the same:
`Traceback (most recent call last):
  File "train.py", line 98, in <module>
    main()
  File "train.py", line 93, in main
    runner.run()
  File "e:\harl\harl\harl\runners\off_policy_base_runner.py", line 283, in run
    self.train()
  File "e:\harl\harl\harl\runners\off_policy_ha_runner.py", line 162, in train
    actions[agent_id], _ = self.actor[
  File "e:\harl\harl\harl\algorithms\actors\hasac.py", line 67, in get_actions_with_logprobs
    logits = self.actor.get_logits(obs, available_actions)
  File "e:\harl\harl\harl\models\policy_models\stochastic_mlp_policy.py", line 78, in get_logits
    return self.act.get_logits(actor_features, available_actions)
  File "e:\harl\harl\harl\models\base\act.py", line 98, in get_logits
    action_distribution = action_out(x, available_actions)
  File "D:\miniconda\envs\harl\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "e:\harl\harl\harl\models\base\distributions.py", line 55, in forward
    return FixedCategorical(logits=x)
  File "D:\miniconda\envs\harl\lib\site-packages\torch\distributions\categorical.py", line 64, in __init__
    super(Categorical, self).__init__(batch_shape, validate_args=validate_args)
  File "D:\miniconda\envs\harl\lib\site-packages\torch\distributions\distribution.py", line 53, in __init__
    raise ValueError("The parameter {} has invalid values".format(param))
ValueError: The parameter logits has invalid values`

**Comment by guazimao** [comment]
I think this is likely due to the unsupported action space. However, it's confusing that the algorithm initially works and the error only appears after some time. Could you provide more detailed information, such as the actor_features before and after the error occurs?

**Comment by captain12321** [comment]
Thanks for your answer, I have modified some of my code and it works out just fine.If this problem happens again in the future,i will let you know.
