### ISSUE TITLE
when I run HASAC with env=pettingzoo_mpe in win11，i meet a problem about .torch.distributions.normal.

### ISSUE THREAD

**Issue by zer0s0** [PKU-MARL/HARL#37]
<img width="877" alt="1" src="https://github.com/PKU-MARL/HARL/assets/106174214/df034113-6160-4acc-9252-814f8d9b5668">

At first, there was no problem, but after 210,000 steps, an error was suddenly reported

<img width="1444" alt="2" src="https://github.com/PKU-MARL/HARL/assets/106174214/4068de9c-b584-424e-9980-0567ec7bf208">

Looks like the problem is caused by the Normal function，the code is in harl/models/policy_models/squashed_gaussian_policy.py line 63.
Is this a problem with the code, or is it an issue with the torch version? my torch version is 2.2.2

**Comment by guazimao** [comment]
Hi. This problem might be caused by improper hyperparameter settings. You can try using the hyperparameters in the "tuned_configs" first. If the problem persists, it might be due to the torch version. I'm using torch 2.1.2.

**Comment by zer0s0** [comment]
> Hi. This problem might be caused by improper hyperparameter settings. You can try using the hyperparameters in the "tuned_configs" first. If the problem persists, it might be due to the torch version. I'm using torch 2.1.2.

The problem has been solved ,thank you
