### ISSUE TITLE
Query about Integration of Transformer Models

### ISSUE THREAD

**Issue by antonio-guillenperez** [PKU-MARL/HARL#38]
Hi,

I am interested in your work on heterogeneous-agent reinforcement learning and the algorithms you have developed. I noticed that your current implementation focuses on algorithms like HAPPO, HATRPO, etc., based on PyTorch. Given the success of transformer models in various domains, are there any plans to incorporate transformer neural networks into your HARL algorithms? This could potentially enhance the capability of handling more complex heterogeneous agent interactions.

Thank you for considering my query.

**Comment by guazimao** [comment]
Hi. Your idea is very interesting. Combining transformer with HARL algorithms indeed has the potential to further improve performance. Your idea is similar to the paper ["Multi-Agent Reinforcement Learning is a Sequence Modeling Problem"](https://arxiv.org/abs/2205.14953), which uses the transformer, sequential update scheme, and PPO update objectives. You can take a look at this paper and its [repo](https://github.com/PKU-MARL/Multi-Agent-Transformer). If you have any further questions, feel free to discuss with me.
