### ISSUE TITLE
About distribution entrophy of Box type

### ISSUE THREAD

**Issue by 7tosmoke** [PKU-MARL/HARL#39]
Thank you for your work first. I'm trying to use your algorithm in my own environment. But I find the distribution entrophy of continues action space always ascends, even in MPE environment. In my view, the entrophy might descend after some episodes. I wonder whether it is right. Looking forward to your reply.

**Comment by guazimao** [comment]
Hello, I find the issue you've discovered very interesting. Could you provide more detailed information? For example, which algorithm are you using and how are the hyperparameters set? This will help us better investigate the problem.
