### ISSUE TITLE
The computational cost of this code

### ISSUE THREAD

**Issue by yiqian-zyq** [PKU-MARL/HARL#41]
Hi, your work is interesting and I hope to replicate and follow your work. But I am worried that my resources are not enough to support this. I hope you can tell me how many GPUs and how much time you need to use for an experiment when conducting this research, especially interesting tasks such as LAG and SMAC. Thank you!

**Comment by guazimao** [comment]
Hello. Reproducing our experiments does not require massive computational resources. A single 3090 GPU is sufficient. Experiments on SMAC typically take a few hours to complete, with off-policy algorithms potentially requiring slightly more time than on-policy ones.
