### ISSUE TITLE
The issue with HASAC

### ISSUE THREAD

**Issue by Nineyears-task** [PKU-MARL/HARL#42]
Hi, I have a question about the HASAC. When I run HASAC on smac, it always stuck with "finish warmup, start training". I didn't have this question when I used HAPPO, which went into the training phase very quickly. I wonder if this is reasonable. Looking forward to your reply! Thank you!

**Comment by guazimao** [comment]
Hello. HASAC is probably not stuck. It requires more training time for the off-policy algorithm compared to on-policy ones. Therefore, you may need to wait a bit longer to see the training results of HASAC.

**Comment by Nineyears-task** [comment]
Thanks for your reply!
