### ISSUE TITLE
Hello author, I encountered the following error while training lag. I hope to receive your guidance

### ISSUE THREAD

**Issue by Turkey-sandwich** [PKU-MARL/HARL#43]
FileNotFoundError: [Errno 2] No such file or directory: './results\\lag\\MultipleCombat-2v2/ShootMissile/HierarchyVsBaseline\\happo\\test_happo_lag\\seed-00001-2024-05-31-21-04-54\\logs/critic/average_step_rewards/critic/average_step_rewards\\events.out.tfevents.1717160888.DESKTOP-R4MOJ38'

**Comment by guazimao** [comment]
Hello, I'm not sure why this file is needed when training lag, as it shouldn't be required normally. Could you provide more detailed information about the training process?
