### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by yuequanfighting** [PKU-MARL/HARL#44]
Why can I still run a non-existent scenario in the MPE environment and get results?
**example:**
Env pettingzoo_mpe Task simple_spread_v2-continuous Algo happo Exp this_not_exit_exp_v5 updates 115/2500 episodes, total num timesteps 460000/10000000, FPS 3755.
Average step reward is -3.8411128520965576.
Some episodes done, average episode reward is -96.49257810195544.

**Comment by Ivan-Zhong** [comment]
Hello. The `exp_name` is used for naming the experiment run. In other words, this is just a name, and users can use this argument to name each run whatever they want. The scenario is specified in the `scenario` argument in `pettingzoo_mpe.yaml`. I hope it helps. :)

**Comment by yuequanfighting** [comment]
> Hello. The `exp_name` is used for naming the experiment run. In other words, this is just a name, and users can use this argument to name each run whatever they want. The scenario is specified in the `scenario` argument in `pettingzoo_mpe.yaml`. I hope it helps. :)

Yeah, I see. Thank you for your help
