### ISSUE TITLE
Bug: There isn't reset of the environment when training

### ISSUE THREAD

**Issue by handleandwheel** [PKU-MARL/HARL#46]
I noticed that with on policy algorithms, the data collection process is done in the `run` function in `OnPolicyBaseRunner`. However, in my experiments, I noticed that my environment would not be reset even if it already gives out `done == True`. Following this clue, I found out that there isn't a reset procudure in the `run` function or any functions called by it that handles the problem.

**Comment by Ivan-Zhong** [comment]
Hi, environments are automatically reset in the `step` function if `done` is `True`. You can take a look at the `harl/envs/env_wrappers.py` to get familiar with the logic ([here](https://github.com/PKU-MARL/HARL/blob/7342761f0098cbb5427f60641fec816b54e27fdb/harl/envs/env_wrappers.py#L166) and [here](https://github.com/PKU-MARL/HARL/blob/7342761f0098cbb5427f60641fec816b54e27fdb/harl/envs/env_wrappers.py#L319)). Let me know if you have further issues. :)
