### ISSUE TITLE
Cannot reproduce the results for MPE

### ISSUE THREAD

**Issue by BolunDai0216** [PKU-MARL/HARL#50]
Hi,

I am trying to reproduce the results for the MPE environments as shown [in the image](https://github.com/PKU-MARL/HARL/blob/main/assets/mpe_learning_curve.jpg) using the default config files.

However, the reward curves for the speaker listener (continuous) environment is very different. Is it possible to share the experiment setup for those curves?

Thanks in advance!

**Comment by Ivan-Zhong** [comment]
Hi, the experiment setups are detailed in README. To reproduce the results, I recommend using the [tuned configs](https://github.com/PKU-MARL/HARL/tree/main/tuned_configs) for those experiments, instead of the default configs. Hope it helps. :)
