### ISSUE TITLE
Incorrect entropy calculation in MuJoCo's HalfCheetah environment when using active_masks

### ISSUE THREAD

**Issue by Jinbo-He** [PKU-MARL/HARL#52]
### Description
I've encountered a significant issue in the MuJoCo HalfCheetah environment related to entropy calculation when using `active_mask`. Specifically, the entropy is incorrectly summed across actions rather than being averaged, resulting in unusually high entropy values ranging from 6000 to 8000 in my tests using the HAPPO algorithm.

### Impact on Rewards
Furthermore, this error in entropy calculation substantially affects the rewards obtained. With the flawed method of summing entropy, the observed rewards in my experiments peak at around 5000. However, when the entropy is correctly averaged, the rewards converge to about 7500. 

### Code
<img width="950" alt="image" src="https://github.com/user-attachments/assets/5172c263-ddfe-48d9-b264-a6164c3de970">

**Comment by Ivan-Zhong** [comment]
Hi, thank you for pointing it out. I will check the code as soon as possible.

**Comment by Ivan-Zhong** [comment]
After checking the code, I found that the previous implementation was indeed incorrect. Now I have fixed it. Thanks again for pointing it out!

**Comment by Jinbo-He** [comment]
> After checking the code, I found that the previous implementation was indeed incorrect. Now I have fixed it. Thanks again for pointing it out!

Thank you for the quick response and fix! I'm glad I could help improve the project.  :smile:
