### ISSUE TITLE
对于训练好的模型， 项目是否包含了测试阶段

### ISSUE THREAD

**Issue by SHENMR-web** [PKU-MARL/HARL#57]
对于训练好的网络参数， 我看到它们保存在了result下面的model里面，项目中是否包含了eval过程，对于训练好的模型直接用于测试呢？

**Comment by guazimao** [comment]
Hi SHENMR-web. We've already included evaluation. The progress.txt file in the results folder records the evaluation results of the model.

**Comment by SHENMR-web** [comment]
非常感谢你的回答
