### ISSUE TITLE
Large performance gap of the code and paper (MADDPG)

### ISSUE THREAD

**Issue by fyqqyf** [PKU-MARL/HARL#7]
Hi, thanks for your impressive work! I'm running MADDPG with tuned configs. I find the results of Walker2d-v2(6x1) are far from the data presented in the paper:
 
![image](https://github.com/PKU-MARL/HARL/assets/48092144/a3a00c98-b1fe-423b-ad55-ba800578a762)
![image](https://github.com/PKU-MARL/HARL/assets/48092144/96077148-460a-4e08-8f59-cd929fee820c)

I think this may be due to the difference in the environment. I use the newest mamujoco 1.1.0, and mujoco version 2.1.0. Could you provide me with more information about the environment?  Thanks again!

**Comment by Ivan-Zhong** [comment]
Hello, it seems that you are using the new mamujoco in Gymnasium Robotics, while our experiments are conducted using the mamujoco code in the `harl/envs/mamujoco` folder. This may cause the difference in performance.

As for our mamujoco environment, the related output of `pip list` is:
```
mujoco                     2.2.0
mujoco-py                  2.1.2.14
```
The mujoco release we are using is mujoco210.

I just run another experiment using the tuned config for Walker2d-v2 & MADDPG, and up to 3 million steps it shows a similar learning pattern with our reported results.

**Comment by Ivan-Zhong** [comment]
Yeah it seems we are using the same environment, and the learning curve I get is

![2023-07-20-21-39-33-Walker2d-v2-6x1-maddpg](https://github.com/PKU-MARL/HARL/assets/37100888/0bfb8651-4abe-40e7-b1ba-37f8c68d612a)

**Comment by kaiyama12345679** [comment]
@fyqqyf Hi, I have the same problem. if you don't mind my asking, would you let me know how you solved this problem?

**Comment by kaiyama12345679** [comment]
I tried Walker2d-v2-6x1 & MADDPG, and the learning curve I got is 
<img width="920" alt="Screenshot 2023-12-22 at 16 40 33" src="https://github.com/PKU-MARL/HARL/assets/106712872/d5f06ecc-080a-4a31-bed4-ee547852c493">

I've checked the environment version, but I couldn't find any differences...

**Comment by BharathRajM** [comment]
> I found the reason, thanks for your help! 😃

Could you please share what the reason was? In a similar position while replicating the paper. Cheers!
