### ISSUE TITLE
Agent taking actions that are unavailable

### ISSUE THREAD

**Issue by giangbang** [PKU-MARL/HARL#8]
Hi, i'm trying to run the code for HAPPO/HATRPO in SMAC. I kept all the tuned configs unchanged, except for the number of parallel environments (`n_rollout_threads`) which I set to 3 to be able to fit in the memory RAM on Kaggle machines. However, among three runs that I have done so far, 2 of them end with something like this (around 150k steps).
```
2764.0s | 450 | Process Process-1:

2764.0s | 451 | Traceback (most recent call last):
2764.0s | 452 | File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2764.0s | 453 | self.run()
2764.0s | 454 | File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 108, in run
2764.0s | 455 | self._target(*self._args, **self._kwargs)
2764.0s | 456 | File "/kaggle/working/HARL/harl/envs/env_wrappers.py", line 172, in shareworker
2764.0s | 457 | ob, s_ob, reward, done, info, available_actions = env.step(data)
2764.0s | 458 | File "/kaggle/working/HARL/harl/envs/smac/StarCraft2_Env.py", line 542, in step
2764.0s | 459 | sc_action = self.get_agent_action(a_id, action)
2764.0s | 460 | File "/kaggle/working/HARL/harl/envs/smac/StarCraft2_Env.py", line 713, in get_agent_action
2764.0s | 461 | assert avail_actions[action] == 1, "Agent {} cannot perform action {}".format(
2764.0s | 462 | AssertionError: Agent 4 cannot perform action 8
2764.1s | 463 | CloseHandler: 127.0.0.1:37902 disconnected
```
The agents are taking invalid actions. Reading through the code, I have noticed that invalid actions are masked with values -1e10. I'm not sure whether this is the cause of the problem, but still, there is a chance, though very rarely, that the actions sampled are actually invalid. Maybe we can make it safer by using the [pytorch MaskedCategorical distribution](https://pytorch.org/rl/reference/generated/torchrl.modules.MaskedCategorical.html), which is just equivalent to 
```python
def forward(self, x, available_actions=None):
    x = self.linear(x)
    if available_actions is not None:
        x[~available_actions.bool()] = float("-inf")
    return FixedCategorical(logits=x)
```
Here is the [script](https://www.kaggle.com/code/banggiangle/harl-testing/log?scriptVersionId=139822963) that i run on Kaggle.

**Comment by Ivan-Zhong** [comment]
Hello. Regarding this problem, there has been a similar issue (https://github.com/oxwhirl/smac/issues/115)(https://github.com/oxwhirl/smac/issues/115) in the SMAC repository, which we would recommend you take a look at. Similar to the authors of SMAC, we have not encountered this error in any of our experiments. Additionally, since we saw your issue, we have run HAPPO on the `10m_vs_11m` task with `n_rollout_threads` set to 3 across python3.7, python3.8, python3.9, and python3.10 environments, with 4 to 5 seeds each. They all run over 9 million steps without errors. Therefore, we suggest you try running the experiments on different machines to see if the error still occurs.

That being said, we appreciate your valuable suggestion of using the PyTorch MaskedCategorical distribution. We will consider switching to it.

**Comment by giangbang** [comment]
Hi @Ivan-Zhong, thank you for your kind reply and your effort to reproduce the error, I really appreciate that. I think maybe this is indeed a machine-dependent error, but somehow I keep encountering this error all the time T _ T.

To save time for anyone who might happen to face the same error in the future, here is what I have tried: First, I changed the masked value in the `FixedCategorical` distribution to `float("-inf")` instead of `-1e10`, but it doesn't work, somehow other logit values are also set to `-inf` as well. Next, I copied the code of `MaskedCategorical` from the torch library, but after an update, the outputs of the network become all `nan`. Finally, I resort to a simple resolution of just doing a rejection sampling: whenever invalid actions are encountered, just reroll the dice to get other actions and it will work fine again.

Here is the code that I added to the `FixedCategorical` class to fix this issue
```python
def repeat_sample(sample_fn, available_action):
    available_action = available_action.bool()
    cnt = 0
    while cnt < 20:
        cnt += 1
        actions = sample_fn()
        valid = torch.gather(available_action, dim=-1, index=actions.unsqueeze(-1))==1
        if valid.all():
            break
    if cnt > 1:
        print("Sample multiple times:", cnt)
    return actions

class FixedCategorical(torch.distributions.Categorical):
    """Modify standard PyTorch Categorical."""
    def __init__(self, *args, mask=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.mask = mask

    def sample(self):
        if self.mask is not None:
            return repeat_sample(super().sample, self.mask).unsqueeze(-1)
        return super().sample().unsqueeze(-1)
```
And in the `forward` function of the `Categorical` class, return the `FixedCategorical` with mask:
```python
    def forward(self, x, available_actions=None):
        x = self.linear(x)
        if available_actions is not None:
            x[available_actions==0] = -1e10
        return FixedCategorical(logits=x, mask=available_actions)

```
This error happens very rarely, only about once per 150/200 k steps, so the computation overhead of resampling hardly registers.

Anyway, thank you for the time you've invested in addressing this matter, i will close it for now.

**Comment by giangbang** [comment]
Hi @Ivan-Zhong, thank you for your kind reply and your effort to reproduce the error, I really appreciate that. I think maybe this is indeed a machine-dependent error, but somehow I keep encountering this error all the time T _ T.

To save time for anyone who might happen to encounter the same error in the future, here is what I have tried: First, I use the masked value in the `FixedCategorical` distribution to `float("-inf")` instead of `-1e10`, but it doesn't work, somehow other values are also set to `-inf` as well. Next, I copy the code of `MaskedCategorical` from torch library, but after an update the output of the network become all `nan`. Finally, I resort to a simple resolution of just doing a rejection sampling: whenever invalid actions are encountered, just reroll the dice to get other actions and it will work fine again.

Here is the code that I added to the `FixedCategorical` class to fix this issue
```python
def repeat_sample(sample_fn, available_action):
    available_action = available_action.bool()
    cnt = 0
    while cnt < 20:
        cnt += 1
        actions = sample_fn()
        valid = torch.gather(available_action, dim=-1, index=actions.unsqueeze(-1))==1
        if valid.all():
            break
    if cnt > 1:
        print("Sample multiple times:", cnt)
    return actions

class FixedCategorical(torch.distributions.Categorical):
    """Modify standard PyTorch Categorical."""
    def __init__(self, *args, mask=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.mask = mask

    def sample(self):
        if self.mask is not None:
            return repeat_sample(super().sample, self.mask).unsqueeze(-1)
        return super().sample().unsqueeze(-1)
```
This error happens very rarely, only about once per 150/200 k steps, so the computation overhead of the resampling hardly registers.

Anyway, thank you for the time you've invested in addressing this issue, i will close it for now.
