### ISSUE TITLE
Wiil hatd3 support discrete action spaces futrue?

### ISSUE THREAD

**Issue by yangtianchangxiao** [PKU-MARL/HARL#9]
Currently, HATD3 only supports continuous actions. Will there be future updates or improvements to support discrete action spaces?

**Comment by guazimao** [comment]
Hi. Yes. In fact, we are currently working on implementing relevant code. Once we verify the correctness of the code and evaluate the algorithms' performance in each benchmark, we will update the code for HATD3, HADDPG, and MADDPG to support discrete action space.
